In [1]:
import pandas as pd
import numpy as np
import kagglehub
import os

In [ ]:
path = kagglehub.dataset_download("leukipp/hourly-stock-prices")
csv = os.path.join(path, '2021', 'AMD' + '.csv')
df = pd.read_csv(csv)
df

,ticker,name,date,open,high,low,close,adjusted close,volume
0,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-01-04 04:00:00-05:00,92.120000,92.250000,91.830000,91.830000,91.830000,0
1,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-01-04 05:00:00-05:00,91.700000,92.340000,91.700000,92.290000,92.290000,0
2,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-01-04 06:00:00-05:00,92.030000,92.600000,92.010000,92.410000,92.410000,0
3,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-01-04 07:00:00-05:00,92.400000,92.410000,92.000000,92.150000,92.150000,0
4,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-01-04 08:00:00-05:00,92.200000,92.260000,92.030000,92.130000,92.130000,0
...,...,...,...,...,...,...,...,...,...
4069,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-12-30 13:30:00-05:00,146.988007,147.429993,146.179993,146.639893,146.639893,4019186
4070,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-12-30 14:30:00-05:00,146.630005,146.770004,145.789993,146.070007,146.070007,4560718
4071,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-12-30 15:30:00-05:00,146.065002,146.240005,144.850006,145.089996,145.089996,4974318
4072,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-12-30 16:00:00-05:00,145.150000,147.100000,137.170900,146.230000,146.230000,0
4073,AMD,"Advanced Micro Devices, Inc. - Common Stock",2021-12-30 17:00:00-05:00,146.200000,146.350000,145.760000,145.780000,145.780000,0

In [3]:
df['date'] = pd.to_datetime(df['date'])

/tmp/ipykernel_95947/3532345252.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['date'] = pd.to_datetime(df['date'])

In [14]:
target_datetime = pd.Timestamp("2021-03-11 10:30:00-05:00")
df[df["date"] >= target_datetime].iloc[0]

ticker                                                    AMD
name              Advanced Micro Devices, Inc. - Common Stock
date                                2021-03-11 10:30:00-05:00
open                                                79.779999
high                                                80.904999
low                                                 79.779999
close                                               80.823997
adjusted close                                      80.823997
volume                                                5969389
Name: 742, dtype: object

In [5]:
df.to_csv('../../data/stock.csv', index=False)